// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQ8FB4bKww-pOkRty-Lp31pDgOqoOiQo',
    appId: '1:376927246431:web:cd4e6b5537ad1ae485a3ea',
    messagingSenderId: '376927246431',
    projectId: 'weather-app-4a511',
    authDomain: 'weather-app-4a511.firebaseapp.com',
    storageBucket: 'weather-app-4a511.firebasestorage.app',
    measurementId: 'G-JV2RM0GJ86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdiX7wN391A6RQB5qclBmcHt0jYprrwg',
    appId: '1:376927246431:android:35838c074027b53585a3ea',
    messagingSenderId: '376927246431',
    projectId: 'weather-app-4a511',
    storageBucket: 'weather-app-4a511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6uOHDItn67aHW4XWgpOzwwdLXBWv5YQ',
    appId: '1:376927246431:ios:408380c91b9a577785a3ea',
    messagingSenderId: '376927246431',
    projectId: 'weather-app-4a511',
    storageBucket: 'weather-app-4a511.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6uOHDItn67aHW4XWgpOzwwdLXBWv5YQ',
    appId: '1:376927246431:ios:408380c91b9a577785a3ea',
    messagingSenderId: '376927246431',
    projectId: 'weather-app-4a511',
    storageBucket: 'weather-app-4a511.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqQ8FB4bKww-pOkRty-Lp31pDgOqoOiQo',
    appId: '1:376927246431:web:0f9ad93b865c809885a3ea',
    messagingSenderId: '376927246431',
    projectId: 'weather-app-4a511',
    authDomain: 'weather-app-4a511.firebaseapp.com',
    storageBucket: 'weather-app-4a511.firebasestorage.app',
    measurementId: 'G-S4DBB486W4',
  );

}